config/routes.rb
Rails.application.routes.draw do
  
  resources :networks

  resources :users
  resources :homes
  
  
  
  root 'application#not_found'
  
  
  
  
  get '/test' => 'homes#index'
  
  get '/cleaneventfile' => 'application#cleaneventfile'
  get '/exporteventfile' => 'application#exporteventfile'
  get '/geteventfile' => 'application#geteventfile'
  
  get '/cleanclickfile' => 'application#cleanclickfile'
  get '/exportclickfile' => 'application#exportclickfile'
  get '/getclickfile' => 'application#getclickfile'
  
  get '/cleanexportfile' => 'application#cleanexportfile'
  get '/cleanlogfile' => 'application#cleanlogfile'
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  get '/getevent' => 'application#getevent'
  get '/event' => 'application#event'
  
  
  get '/getclick' => 'application#getclick'
  get '/click' => 'application#click'
  
  
  
  
  
    
  
  
  
  
  
  
   
  get '*unmatched_route' => 'application#not_found'

end

app/models/network.rb
class Network < ActiveRecord::Base
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
  before_action :set_network, only: [:show, :edit, :update, :destroy]
  before_action :authuser
  layout "home"
  
  # caches_page :campaigns
  # caches_action :getcampaigns
  
  
  def sogou_api(username,password,token,api_string)            
    @sogou_api = Savon.client(
      wsdl: "http://api.agent.sogou.com:80/sem/sms/v1/"+api_string+"?wsdl",
      pretty_print_xml: true,
      log: true,
      env_namespace: :soap,
      namespaces: {"xmlns:common" => "http://api.sogou.com/sem/common/v1"},
      soap_header: { 
        "common:AuthHeader" => {
          'common:token' => token,
          'common:username' => username,
          'common:password' => password
        }
      }
    )    
  end
  
  def threesixty_api( api_key, access_token, service, method, params = {})
    url = "https://api.e.360.cn/2.0/#{service}/#{method}"
      response = HTTParty.post(url,
            timeout: 300, 
            body: params,
            headers: {
                        'apiKey' => api_key, 
                        'accessToken' => access_token, 
                        'serveToken' => Time.now.to_i.to_s  
                      })
      
      @response = response                
      return response.parsed_response
  end
  
  def threesixty_api_login(username,password,api_key,api_secret)
    cipher_aes = OpenSSL::Cipher::AES.new(128, :CBC)
    cipher_aes.encrypt
    cipher_aes.key = api_secret[0,16]
    cipher_aes.iv = api_secret[16,16]
    encrypted = (cipher_aes.update(Digest::MD5.hexdigest(password)) + cipher_aes.final).unpack('H*').join
    url = "https://api.e.360.cn/account/clientLogin"
    response = HTTParty.post(url,
        :timeout => 300,
        :body => {
        :username => username,
        :passwd => encrypted[0,64]
        },
        :headers => {'apiKey' => api_key }
    )
    return response.parsed_response
  end
  
  def bulkuploadedit
    
  end
  
  def bulkuploadadd
      
      
  end
  # def bulkjob
#     
      # file = params[:file]
      # @upload_type = params[:upload_type]
      # @account_id = params[:account]
      # @status = params[:status]
#       
      # begin
          # xlsx = Roo::Spreadsheet.open(file.path, extension: :xlsx)
      # rescue Exception
          # # return render :text => "File type error, Exexl File(.xlsx) only."
          # data = {:message => "File type error, Exexl File(.xlsx) only.", :status => "false", :sdsf => @upload_type}
          # return render :json => data, :status => :ok
      # end
#       
      # data = {:message => "Your Request is invalid.", :status => "false", :sdsf => @upload_type}
      # return render :json => data, :status => :ok
  # end
  def resumebulkjob
      @_id = params[:_id]
      
      @current_jobs = @db2["bulkjob"].find('_id' => BSON::ObjectId.from_string(@_id.to_s)).update_one('$set'=> { 'status' => 0, 'last_update' => @now})
      @db2.close
      
      if @current_jobs.count.to_i > 0
          data = {:message => "Your Request is complete.", :status => "true"}
      else
          data = {:message => "Your Request is invalid.", :status => "false"}
      end
      return render :json => data, :status => :ok
  end
  
  
  def cancelbulkjob
      @_id = params[:_id]
      
      @current_jobs = @db2["bulkjob"].find('_id' => BSON::ObjectId.from_string(@_id.to_s)).update_one('$set'=> { 'status' => 5, 'last_update' => @now})
      @db2.close
      
      if @current_jobs.count.to_i > 0
          data = {:message => "Your Request is complete.", :status => "true"}
      else
          data = {:message => "Your Request is invalid.", :status => "false"}
      end
      return render :json => data, :status => :ok
  end
  
  
  def getadvancesearch
      
      csv_array = []     
      data_array = []
      network_id_list = []
      network_list_hash = Hash.new()
      @draw = params[:draw]
      @length = params[:length]
      @skip_data = params[:start]
      @start_date = params[:start_date]
      @end_date = params[:end_date]
      @csv = params[:csv]
      @export_csv_start_date = nil 
      @export_csv_end_date = nil
      @order = params[:order]
      
      
      if @end_date.nil?
          request_start_date = @today
          @export_csv_end_date = request_start_date
          @end_date = request_start_date.strftime("%Y-%m-%d")+" 23:59:59 CST"
      else
          session[:adv_end_date] = @end_date.to_date
          @export_csv_end_date = @end_date.to_date
          @end_date = @end_date.to_date
          @end_date = @end_date.strftime("%Y-%m-%d")+" 23:59:59 CST"
      end
      @export_csv_end_date = @export_csv_end_date.strftime("%Y-%m-%d")+" 23:59:59 CST"
      


      if @start_date.nil?
          request_start_date = @today - 9.days
          @export_csv_start_date = @today - 9.days
          @start_date = request_start_date.strftime("%Y-%m-%d")+" 00:00:00 CST"
      else
          session[:adv_start_date] = @start_date.to_date
          @export_csv_start_date = @start_date.to_date
          @start_date = @start_date.to_date
          @start_date = @start_date.strftime("%Y-%m-%d")+" 00:00:00 CST"
      end
      
      @export_csv_start_date = @export_csv_start_date.strftime("%Y-%m-%d")+" 00:00:00 CST"


      @channel_array = params[:channel_array]
      @filter_account_array = params[:account_array]
      @user_network_array = []

      if !@filter_account_array.nil?
          @filter_account_array.each do |filter_network|
              @user_network_array << filter_network.to_i
          end
      else
          @user_network = @db[:network_user].find('user' => session[:user_id].to_i)
          @db.close
          
          @user_network.each do |user_network|
              @user_network_array << user_network["network_id"]
          end
      end

      @user_network_array.each do |usernetwork|
          @total_network = @db[:network].find('id' => usernetwork,'type' => { "$in" => @channel_array})
          @db.close
          @total_network.each do |network_d|
            network_id_list.push(network_d["id"])
          end
      end

      @network = @db[:network].find('type' => { "$in" => @channel_array})
      @network.each do |network_d|
        network_list_hash[network_d['id'].to_s] = network_d['name'].to_s
      end
      
      @advancesearchjob = @db[:advancesearchjob].find('request_date'  => { '$gte' => @start_date.to_s, '$lt' => @end_date.to_s },'network_id' => {"$in" => network_id_list}).sort({ request_date: -1 })
      @db.close
      
      recordsTotal = @advancesearchjob.count.to_i
      
      if @advancesearchjob.count.to_i > 0 
        
          @advancesearchjob.each do |advancesearchjob_d|

          filter_object = ""
          filter_object_csv = ""

          if advancesearchjob_d["filter_object"].to_s != ""
                          
            advancesearchjob_d["filter_object"].each do |filter|
              filter_e =  eval(filter[1].to_s)
              name = filter_e["name"]
              rule = filter_e["rule"]
              value = filter_e["value"]
                            
              name = name.slice(0,1).capitalize + name.slice(1..-1)
              rule = rule.to_s.gsub("**", 'contain')
                            
              filter_object = filter_object + name.to_s + " " + rule.to_s + " " + value.to_s + "<br>"
              filter_object_csv = filter_object_csv + name.to_s + " " + rule.to_s + " " + value.to_s + "\n"
              #filter_object = filter_object + "<br>"
            end                     
          end
          job_process = ''
          if advancesearchjob_d["process"].to_i == 0 then
            job_process = 'Pending'
          elsif advancesearchjob_d["process"].to_i == 1 then
            job_process = 'Processing'
          elsif advancesearchjob_d["process"].to_i == 2 then
            job_process = 'Done'
          elsif advancesearchjob_d["process"].to_i == 3 then
            job_process = 'Cancel'
          end


          csv_array << [advancesearchjob_d['network_id'],network_list_hash[advancesearchjob_d['network_id'].to_s],advancesearchjob_d['apply_level'],advancesearchjob_d['start_date'],advancesearchjob_d['end_date'],advancesearchjob_d['edit_status'],advancesearchjob_d['action'],filter_object_csv,job_process,advancesearchjob_d['request_date']]
          data_array  << [advancesearchjob_d['network_id'],network_list_hash[advancesearchjob_d['network_id'].to_s],advancesearchjob_d['apply_level'],advancesearchjob_d['start_date'],advancesearchjob_d['end_date'],advancesearchjob_d['edit_status'],advancesearchjob_d['action'],filter_object,job_process,advancesearchjob_d['msg'].to_s,advancesearchjob_d['request_date'],advancesearchjob_d['last_update'],advancesearchjob_d['_id'].to_s]
        end
      end

      if @csv.to_i == 1
          if @export_csv_start_date == @export_csv_end_date then
            @filename = "advance_search_job_" + @export_csv_start_date 
          else
            @filename = "advance_search_job_" + @export_csv_start_date + "-" + @export_csv_end_date + ")"
          end
          head = ["\xEF\xBB\xBFNetwork ID", "\xEF\xBB\xBFNetwork Name", "\xEF\xBB\xBFApply Level", "\xEF\xBB\xBFFrom", "To", "Job","Action", "Filter", "Process", "Request Date"]
          # csv(@filename,head,csv_array)
          excel(@filename,head,csv_array)
      else
        
          if !@order.nil?
              @sort_column = @order["0"]["column"]
              @sort_method = @order["0"]["dir"]
            
              if @sort_method.to_s == "asc" then
                data_array = data_array.sort_by{|k|k[@sort_column.to_i]}      
              else
                data_array = data_array.sort_by{|k|k[@sort_column.to_i]}.reverse
              end
          end        
          @data = {
                  :draw => @draw,
                  :recordsTotal => recordsTotal,
                  :recordsFiltered => data_array.count.to_i,

app/helpers/networks_helper.rb
module NetworksHelper
end

app/views/networks/_campaign_tab_menu.html.erb
<%
@status = "Active"

if @type.to_s == 'sogou'
	@campaign.each do |campaign|
		@title = campaign["campaign_name"]
		@budget = campaign["budget"]
		# @budget = @budget / 30
	                                      
		if campaign["pause"].to_s == 'true'  
			@status = "Inactive"
		end
	end
end

if @type.to_s == '360' || @type.to_s == 'threesixty'
	@campaign.each do |campaign|
		@title = campaign["campaign_name"]
		@budget = campaign["budget"]
		# @budget = @budget / 30
	                                      
		if campaign["status"].to_s == '暂停'  
			@status = "Inactive"
		end
	end
end
%>

<ol class="breadcrumb">
	<!-- <li><a href="/campaigns">Campaigns</a></li> -->
	<li><a href="/channel/<%=@network_id%>/campaigns"><%=@network_name%></a></li>
	
	<% if @adgroup_id.to_i <= 0 %>
			<li class="active"><strong><i><%=@title.to_s%></i></strong></li>
	<% else %>
			<%
				@adgroup_name = ""
				@adgroup_status = "Active"
				@db_type = @type.to_s
				
				if @type.to_s == "threesixty"
					@db_type = "360"
				end
				
				db_name = "adgroup_" + @db_type.to_s + "_" + @network_id.to_s
				 
				if @type.to_s == 'sogou'
				 
					@adgroup = @db[db_name].find('cpc_grp_id' => @adgroup_id.to_i)
	          		@db.close
	          		
	          		if @adgroup.count.to_i > 0
			            @adgroup.each do |adgroup_d|
			            	@adgroup_name = adgroup_d['name']
			            	@adgroup_status = adgroup_d['status']
			            end
		           	end
          		
          		elsif @type.to_s == 'threesixty'
          			
          			@adgroup = @db[db_name].find('adgroup_id' => @adgroup_id.to_i)
	          		@db.close
	          		
	          		if @adgroup.count.to_i > 0
			            @adgroup.each do |adgroup_d|
			            	@adgroup_name = adgroup_d['adgroup_name']
			            	@adgroup_status = adgroup_d['status']
			            end
		           	end
	          		
          		end
			%>
			
			<li class="active"><a href="/campaigns/<%=@id%>/<%=@type%>/<%=@network_id%>/adgroup"><%=@title.to_s%></a></li>
			<li class="active"><strong><i><%=@adgroup_name.to_s%></i></strong></li>
	<% end %>
</ol>
<% if @adgroup_id.to_i <= 0 %>
		<div class="content_title under_breadcrumb"><%=@title.to_s%></div>
<% else %>
		<div class="content_title under_breadcrumb"><%=@adgroup_name.to_s%></div>
<% end %>

<div class="status_container">
	<% if @adgroup_id.to_i <= 0 %>
		<div class="pull-left">Campaign Status: <%=@status.to_s%> <span class="status_point <%=@status.to_s.downcase%>"> </span></div>
		<div class="budget_container pull-left">Campaign Daily Budget: <span class="red_text"><%=@budget%> <%=@currency.to_s.upcase%></span></div>
	<% else %>
		<% 
		if @adgroup_status.to_s == "21" || @adgroup_status.to_s == "启用"
			@adgroup_status = "Active"
		else
			@adgroup_status = "Inactive" 
		end 
		%>
		<div class="pull-left">Adgroup Status: <%=@adgroup_status.to_s%> <span class="status_point <%=@adgroup_status.to_s.downcase%>"> </span></div>
	<% end %>
	<div class="clearfix"></div>
</div>


<ul class="tab_menu">
	<% if @adgroup_id.to_i <= 0 %>
			<li><a class="tab_tag overview_tag" href="/campaigns/<%=@id%>/<%=@type%>/<%=@network_id%>/overview">Overview</a></li>
			<li><a class="tab_tag setting_tag" href="/campaigns/<%=@id%>/<%=@type%>/<%=@network_id%>/setting">Settings</a></li>
			<li><a class="tab_tag adgroups_tag" href="/campaigns/<%=@id%>/<%=@type%>/<%=@network_id%>/adgroup">Ad Groups</a></li>
	<% end %>
	
	<% if @adgroup_id.to_i > 0 %>
			<li><a class="tab_tag ads_tag" href="/campaigns/<%=@id%>/<%=@type%>/<%=@network_id%>/adgroup/<%=@adgroup_id%>/ads">Ads</a></li>
			<li><a class="tab_tag keywords_tag" href="/campaigns/<%=@id%>/<%=@type%>/<%=@network_id%>/adgroup/<%=@adgroup_id%>/keyword">Keywords</a></li>
	<% else %>
			<li><a class="tab_tag ads_tag" href="/campaigns/<%=@id%>/<%=@type%>/<%=@network_id%>/ads">Ads</a></li>
			<li><a class="tab_tag keywords_tag" href="/campaigns/<%=@id%>/<%=@type%>/<%=@network_id%>/keyword">Keywords</a></li>
	<% end %>
</ul>

<script>
	if(/\/campaigns\/\w*\/\w*\/\w*\/overview/i.test(window.location.href)){
		$(".overview_tag").addClass("active");
	}
	else if(/\/campaigns\/\w*\/\w*\/\w*\/setting/i.test(window.location.href)){
		$(".setting_tag").addClass("active");
	}
	else if(/\/campaigns\/\w*\/\w*\/\w*\/adgroup/i.test(window.location.href)){
		if(/keyword/i.test(window.location.href)){
			$(".keywords_tag").addClass("active");
		}else if(/ads/i.test(window.location.href)){
			$(".ads_tag").addClass("active");
		}else{
			$(".adgroups_tag").addClass("active");
		}
	}
	else if(/\/campaigns\/\w*\/\w*\/\w*\/ads/i.test(window.location.href)){
		$(".ads_tag").addClass("active");
	}else if (/\/campaigns\/\w*\/\w*\/\w*\/keyword/i.test(window.location.href)){
		$(".keywords_tag").addClass("active");
	}
</script>

app/views/networks/bulkuploadadd.html.erb
<div class="content_title">Bulk Upload</div>
<ul class="tab_menu">
	<li><a class="tab_tag history_log_tag active" href="javascript:;">Add</a></li>
	<li><a class="tab_tag history_log_tag" href="/bulkupload/edit">Edit</a></li>
	<li><a class="tab_tag search_tag" href="/bulk/summary">Summary</a></li>
</ul>

<%
port_array = [81,83]
# port_array = [81,83,85,87]
random_port = port_array.shuffle.sample
%>

<div class="content_outer">
	<div class="content_core">
		
		<div class="content_core_title">Use spreadsheets to make bulk changes to your campaigns</div>
		<hr>
		
		<div class="content_form">
			
			<div class="content_form">
				<form action="http://china.adeqo.com:<%=random_port.to_s%>/bulkjob" method="post" id="uploadForm" enctype="multipart/form-data" autocomplete="off" target="hiddenUploadIframe">
					
					<div class="form_row">
						<div class="content_form_label">
							<label class="form_label">Upload type:</label>
							<div class="clearfix"></div>
						</div>
						
						<div class="content_form_input">
							<input type="radio" name="upload_type" value="campaigns" checked> <label>Campaigns</label>
							<input type="radio" name="upload_type" value="adgroup"> <label>Ad Groups</label>
							<input type="radio" name="upload_type" value="ad"> <label>Ads</label>
							<input type="radio" name="upload_type" value="keyword"> <label>Keywords</label>
						</div>
						<div class="clearfix"></div>
					</div>
					<hr>
					
					<div class="form_row">
						<div class="content_form_label" style="min-width:400px;">
							<label class="form_label">Please select channel and account:</label>
							<div class="clearfix"></div>
						</div>
						
						<div class="content_form_input">
							<select class="form_field" name="account" id="account">
								<%
								usernetwork_array = []
								@user_network = @db[:network_user].find('user' => session[:user_id].to_i)
								@db.close
								
								@user_network.each do |usernetwork|
									usernetwork_array << usernetwork["network_id"].to_i
								end
								
								# @networks = @db[:network].find('company_id' => @user_company_id.to_i)
								@networks = @db[:network].find('id' => { "$in" => usernetwork_array})
								if @networks.count.to_i > 0
									@networks.each do |network|
										%><option name="<%=network['type']%>" value="<%=network['id']%>"><%=network['name']%></option><%
									end
								end
								%>
							</select>
						</div>
						<div class="clearfix"></div>
						
					</div>
					<hr>
					
					<div class="form_row">
						<strong>Upload</strong>
					</div>
					<div class="form_row">
						Select a file containing the changes to your campaign. Supported format - .xlsx<br />Please use this template <a href="/csv_template/Bulk_Add_Excel_Template.zip">here</a> (select channel / account first to view the correct template)
					</div>
					<div class="form_row upload-row">
						<input type="hidden" name="type" />
						<input type="file" name="file"/>
						<span id="upload_error" class="error_message"></span>
					</div>
					
					<hr>
					
					<div class="form_row">
						<div class="content_form_label">
							<label class="form_label">Post to Channel Options</label>
							<div class="clearfix"></div>
						</div>
						
						<div class="content_form_input">
							<input type="radio" name="status" value="0" checked> Upload changes in "Queued" status
							<br />
							<input type="radio" name="status" value="3"> Upload changes in "On Hold" status
							
						</div>
						<div class="clearfix"></div>
					</div>
					
					<input type="hidden" name="bulk_type" value="add">
					<input type="hidden" name="user_email" value="<%=@current_user_email.to_s%>"> 
					
					
					<div class="form_row">&nbsp;</div>
					<div class="form_row">
						<button type="button" class="button red_button submit_button" onclick="submitbulkUpload('apply');">Process</button>
						<button type="button" class="button white_button cancel_button" onclick="resetBulkUploadForm();">Cancel</button>
					</div>
					
				</form>
				
				<iframe id="hiddenUploadIframe" name="hiddenUploadIframe" height="0" width="0" frameborder="0" scrolling="yes"></iframe>
			</div>
			
			
		</div>
	</div>
</div>

app/views/networks/bulkuploadedit.html.erb
<div class="content_title">Bulk Upload</div>
<ul class="tab_menu">
	<li><a class="tab_tag history_log_tag" href="/bulkupload/add">Add</a></li>
	<li><a class="tab_tag history_log_tag active" href="javascript:;">Edit</a></li>
	<li><a class="tab_tag search_tag" href="/bulk/summary">Summary</a></li>
</ul>

<%
port_array = [81,83]
# port_array = [81,83,85,87]
random_port = port_array.shuffle.sample
%>

<div class="content_outer">
	<div class="content_core">
		
		<div class="content_core_title">Use spreadsheets to make bulk changes to your campaigns</div>
		<hr>
		
		<div class="content_form">
			
			<div class="content_form">
				<form action="http://china.adeqo.com:<%=random_port.to_s%>/bulkjob" method="post" id="uploadForm" enctype="multipart/form-data" autocomplete="off" target="hiddenUploadIframe">
					
					<div class="form_row">
						<div class="content_form_label">
							<label class="form_label">Upload type:</label>
							<div class="clearfix"></div>
						</div>
						
						<div class="content_form_input">
							<input type="radio" name="upload_type" value="campaigns" checked> <label>Campaigns</label>
							<input type="radio" name="upload_type" value="adgroup"> <label>Ad Groups</label>
							<input type="radio" name="upload_type" value="ad"> <label>Ads</label>
							<input type="radio" name="upload_type" value="keyword"> <label>Keywords</label>
						</div>
						<div class="clearfix"></div>
					</div>
					<hr>
					<!--
					<div class="form_row">
						<div class="content_form_label" style="min-width:400px;">
							<label class="form_label">Please select channel and account:</label>
							<div class="clearfix"></div>
						</div>
						
						<div class="content_form_input">
							<select class="form_field" name="account" id="account">
								<%
								usernetwork_array = []
								@user_network = @db[:network_user].find('user' => session[:user_id].to_i)
								@db.close
								
								@user_network.each do |usernetwork|
									usernetwork_array << usernetwork["network_id"].to_i
								end
								
								# @networks = @db[:network].find('company_id' => @user_company_id.to_i)
								@networks = @db[:network].find('id' => { "$in" => usernetwork_array})
								if @networks.count.to_i > 0
									@networks.each do |network|
										%><option name="<%=network['type']%>" value="<%=network['id']%>"><%=network['name']%></option><%
									end
								end
								%>
							</select>
						</div>
						<div class="clearfix"></div>
						
					</div>
					<hr>
					-->
					
					<div class="form_row">
						<strong>Upload</strong>
					</div>
					<div class="form_row">
						Select a file containing the changes to your campaign. Supported format - .xlsx<br />
						<a href="/csv_template/Bulk_Edit_Excel_Template.zip">Example Here</a>
					</div>
					<div class="form_row upload-row">
						<input type="hidden" name="type" />
						<input type="file" name="file"/>
						<span id="upload_error" class="error_message"></span>
					</div>
					
					<hr>
					
					<div class="form_row">
						<div class="content_form_label">
							<label class="form_label">Post to Channel Options</label>
							<div class="clearfix"></div>
						</div>
						
						<div class="content_form_input">
							<input type="radio" name="status" value="0" checked> Upload changes in "Queued" status
							<br />
							<input type="radio" name="status" value="3"> Upload changes in "On Hold" status
							
						</div>
						<div class="clearfix"></div>
					</div>
					
					<input type="hidden" name="bulk_type" value="edit">
					<input type="hidden" name="user_email" value="<%=@current_user_email.to_s%>"> 
					
					
					<div class="form_row">&nbsp;</div>
					<div class="form_row">
						<button type="button" class="button red_button submit_button" onclick="submitbulkUpload('apply');">Process</button>
						<button type="button" class="button white_button cancel_button" onclick="resetBulkUploadForm();">Cancel</button>
					</div>
					
				</form>
				
				<iframe id="hiddenUploadIframe" name="hiddenUploadIframe" height="0" width="0" frameborder="0" scrolling="yes"></iframe>
			</div>
			
			
		</div>
	</div>
</div>

app/views/networks/edit.html.erb
<h1>Editing network</h1>

<%= render 'form' %>

<%= link_to 'Show', @network %> |
<%= link_to 'Back', networks_path %>

app/views/networks/new.html.erb
<h1>New network</h1>

<%= render 'form' %>

<%= link_to 'Back', networks_path %>