config/routes.rb
Rails.application.routes.draw do
  
  resources :networks

  resources :users
  resources :homes
  
  
  
  root 'application#not_found'
  
  
  
  
  get '/test' => 'homes#index'
  
  get '/cleaneventfile' => 'application#cleaneventfile'
  get '/exporteventfile' => 'application#exporteventfile'
  get '/geteventfile' => 'application#geteventfile'
  
  get '/cleanclickfile' => 'application#cleanclickfile'
  get '/exportclickfile' => 'application#exportclickfile'
  get '/getclickfile' => 'application#getclickfile'
  
  get '/cleanexportfile' => 'application#cleanexportfile'
  get '/cleanlogfile' => 'application#cleanlogfile'
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  get '/getevent' => 'application#getevent'
  get '/event' => 'application#event'
  
  
  get '/getclick' => 'application#getclick'
  get '/click' => 'application#click'
  
  
  
  
  
    
  
  
  
  
  
  
   
  get '*unmatched_route' => 'application#not_found'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :destroy]
  # before_action :authuser, only: [:index,:show,:updatepw,:updatemail,:companyuser]
  
  before_action :authuser, except: [:createnewuser,:logout,:login]
  layout "home" 
  
  require "azure"
  
  require 'rubygems'
  require 'mongo'
  
  def portfolio
    
  end
  
  def tracking
    
  end
  
  def account
    @current_user_network = @db[:network].find('company_id' => @user_company_id)
    @db.close
  end
  
  
  def edituser
    
      if @user_role == "read"
        data = {:message => "You cant delete anything", :status => "false"}
        return render :json => data, :status => :ok
      end
    
      user_id = params[:id]
      user = @db[:user].find('id' => user_id.to_i)
      
      if user.count.to_i != 1
          data = {:message => "Wrong input", :status => "false"}
          return render :json => data, :status => :ok
      else
        
          @update_name =  params[:signup_name]
          @update_email =  params[:signup_email]
          @update_password =  params[:signup_password]
          @update_user_role =  params[:user_role]
          
          if @user_role == "read"
              data = {:message => "You can't edit anything", :status => "false"}
              return render :json => data, :status => :ok 
          end
          
          
          if @update_password.to_s != ""
              @encrypted_password = BCrypt::Password.create(@update_password.to_s)
              @db[:user].find('id' => user_id.to_i).update_one('$set'=> { 'password' => @encrypted_password })
          end
          
          @db[:user].find('id' => user_id.to_i).update_one('$set'=> { 'email' => @update_email, 'username' => @update_name, 'role' => @update_user_role })
          @db.close
          
          data = {:message => "Done", :status => "true", :user => user}
          return render :json => data, :status => :ok 
          
      end
  end
  
  
  def switchuserstatus
    
      if @user_role == "read"
        data = {:message => "You cant edit anything", :status => "false"}
        return render :json => data, :status => :ok
      end
    
      user_id = params[:id]
      user_status = params[:status]
      
      user = @db[:user].find('id' => user_id.to_i)
      @db.close
      
      if user.count.to_i != 1
          data = {:message => "Wrong input", :status => "false"}
          return render :json => data, :status => :ok
      else
          @db[:user].find('id' => user_id.to_i).update_one('$set'=> { 'status' => user_status.to_s })
          @db.close
          
          data = {:message => "Done", :status => "true"}
          return render :json => data, :status => :ok 
      end
  end
  
  
  def getuser
    
      if @user_role == "read"
        data = {:message => "You cant edit anything", :status => "false"}
        return render :json => data, :status => :ok
      end
      
      user_id = params[:id]
      sub_users = @db[:user].find('id' => user_id.to_i)
      @db.close
      
      if sub_users.count.to_i != 1
          data = {:message => "Wrong input", :status => "false"}
          return render :json => data, :status => :ok
      else          
          data = {:message => "Done", :status => "true", :user => sub_users}
          return render :json => data, :status => :ok 
      end
  end
  
  
  def user
    
    @current_user.each do |user|
      @current_user_password = user["password"]
      @userid = user["id"]
      @company_id = user["company_id"] 
    end
    
    @sub_users = @db[:user].find('company_id' => @company_id)
    @db.close
    
  end
  
  
  def updatepw
    
    @input_current_pw =  params[:up_c_password]
    @input_new_pw =  params[:up_n_password]
    
    @current_user.each do |user|
      @current_user_password = user["password"]
      @id = user["id"]
    end
    
    @encrypted_password = BCrypt::Password.new(@current_user_password)
    @auth = (@encrypted_password == @input_current_pw)
    
    if @auth == false
      data = {:message => "Current PW not correct", :status => "false"}
      return render :json => data, :status => :ok
    end
    
    @encrypted_password = BCrypt::Password.create(@input_new_pw.to_s)
    
    @db[:user].find('id' => session[:user_id]).update_one('$set'=> { 'password' => @encrypted_password })
    @db.close
    @db[:user].find('id' => session[:user_id]).update_one('$set'=> { 'last_login' => @now })
    @db.close
    
    data = {:message => "PW Updated", :status => "true"}
    return render :json => data, :status => :ok
  end
  
  
  
  
  
  def updatemail
    #put logout here to avoid hack, this function is not in use for now
    
    session[:user_id] = nil
    return redirect_to "/"
    # @input_current_pw =  params[:um_c_password]
    # @input_new_email =  params[:um_n_mail]
#    
    # @current_user.each do |user|
      # @current_user_password = user["password"]
      # @id = user["id"]
    # end
#    
    # @encrypted_password = BCrypt::Password.new(@current_user_password)
    # @auth = (@encrypted_password == @input_current_pw)
#     
    # if @auth == false
      # data = {:message => "Current PW not correct"}
      # return render :json => data, :status => :ok
    # end
#     
    # @db[:user].find('id' => session[:user_id]).update_one('$set'=> { 'password' => @input_new_email })
  end
  
  
  
  def createcompany
  end
  
  
  
  
  
  def removeuser
    
    
    if @user_role != "super"
      # session[:user_id] = nil
      # return redirect_to "/"
      data = {:message => "You cant remove anything", :status => "false"}
      return render :json => data, :status => :ok
    end
    
    @id =  params[:remove_userid]
    @db[:user].find('id' => @id.to_i).delete_one
    @db.close
    # @result = @db[:user].find('id' => @id)
    
    @db[:network_user].find('user' => @id.to_i).delete_many
    @db.close
    
    data = {:message => "Removed", :status => "true", :id => @id}
    return render :json => data, :status => :ok
  end
  
  def createnewuser
    # Mongoid.database.connection.close 
    last_user_id = get_last_id("user")
    last_company_id = get_last_id("company")
    
    @username =  params[:signup_name]
    
    @email =  params[:signup_email]
    @password = params[:signup_password]
    
    @encrypted_password = BCrypt::Password.create(@password.to_s)

    @user_role = params[:user_role]
    @company_role = params[:company_role]
    
    @company = params[:signup_company]
    @user_company_id = params[:signup_company_id]
    
    @sub_user = params[:sub_user]
    
    
    current_user = @db[:user].find('email' => @email.to_s)
    @db.close
    current_company = @db[:company].find('name' => @company.to_s)
    @db.close
    
    if current_company.count == 1
      data = {:message => "This Company exist, can't use this name", :status => "false"}
      return render :json => data, :status => :ok
    end
     
    if current_user.count == 1
      data = {:message => "This user exist, use another email", :status => "false"}
      return render :json => data, :status => :ok      
    else
      
      @user_id = last_user_id.to_i + 1
      @company_id = last_company_id.to_i + 1
      
      if @user_company_id.nil?
          @user_company_id = @company_id
      end
      
      if @username.nil?
          @username = @email
      end
      
      if !@user_role.nil?
        @db[:user].insert_one({ id: @user_id.to_i, company_id: @user_company_id.to_i, email: @email, username: @username, password: @encrypted_password, role: @user_role.to_s, status: 'start', create_date: @now, last_login: @now })
        @db.close
        update_last_id("user",@user_id)
      end
      
      if !@company_role.nil?
        @db[:company].insert_one({ id: @company_id.to_i, name: @company.to_s, user_id: @user_id, role: @company_role.to_s, status: 'start', create_date: @now })
        @db.close
        update_last_id("company",@company_id)
      end
      
      if @sub_user.to_i == 0
          session[:user_id] = @user_id
          session[:user_role] = @user_role.to_s
      end 
           
      data = {:message => "Add User Done", :user_id => @user_id, :company_id => @company_id, :status => "true"}
      return render :json => data, :status => :ok
      
    end
  end
  
  def logout
    session[:user_id] = nil
    session[:user_network_id_array] = nil
    return redirect_to "/"
  end
  
  
  def login
    session[:user_network_id_array] = nil
    @email =  params[:login_email]
    @password = params[:login_password]
    
    if params[:login_email].nil?
      data = {:message => "Input email empty", :status => "false"}
      return render :json => data, :status => :ok
    end
    
    if params[:login_password].nil?
      data = {:message => "Input password empty", :status => "false"}
      return render :json => data, :status => :ok  
    end
    
    
    @current_user = @db[:user].find('email' => @email)
    @db.close
    @current_user_count = @current_user.count.to_i
    
    if @current_user_count == 0
      data = {:message => "This user was not found in the system.", :status => "false"}
      return render :json => data, :status => :ok
    end
    
    if @current_user_count > 1
      data = {:message => "Something Wrong with your Account, please call us.", :status => "false"}
      return render :json => data, :status => :ok
    end
    
    @current_user.each do |user|
      @current_user_password = user["password"]
      @id = user["id"]
    end
    
    @encrypted_password = BCrypt::Password.new(@current_user_password)
    @auth = (@encrypted_password == @password)
    
    # data = {:encrypted_password => @encrypted_password, :auth => @auth, :current_user_password => @current_user_password, :input_password => @password}
    # return render :json => data, :status => :ok
    
    if @auth != true

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_account_tab_menu.html.erb
<ul class="tab_menu">
	<li><a class="tab_tag ad_account_tag" href="/account">Ad Accounts</a></li>
	<li><a class="tab_tag user_tag" href="/account/user">Users</a></li>
	<li><a class="tab_tag portfolio_tag" href="/account/portfolio">Portfolio</a></li>
	<li><a class="tab_tag tracking_tag" href="/account/tracking">Tracking</a></li>
	<li><a class="tab_tag password_tag" href="/account/password">Password</a></li>
</ul>


<script>
	if(/\/account\/user/i.test(window.location.href)){
		$(".user_tag").addClass("active");
	}
	else if(/\/account\/portfolio/i.test(window.location.href)){
		$(".portfolio_tag").addClass("active");
	}
	else if(/\/account\/tracking/i.test(window.location.href)){
		$(".tracking_tag").addClass("active");
	}
	else if(/\/account\/password/i.test(window.location.href)){
		$(".password_tag").addClass("active");
	}else if (/account/i.test(window.location.href)){
		$(".ad_account_tag").addClass("active");
	}
</script>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

app/views/users/editpassword.html.erb
<div class="content_title">Account Settings</div>
<%= render partial: "account_tab_menu.html.erb" %>

<div class="content_outer">
	<div class="content_core">
		<div class="content_core_big_title">Change Adeqo Account Password</div>
		<hr/>
		<div class="content_form">
			<form action="" method="post" id="resetPasswordForm" autocomplete="off">
				<div class="form_row">
					<div class="content_form_label pull-left">
						<label for="reset_current_password" class="form_label pull-right">Current Password:</label>
						<div class="clearfix"></div>
					</div>
					<div class="content_form_input pull-left">
						<input id="reset_current_password" name="up_c_password" type="password" autocomplete="off" class="form_field"/><br/>
				 		<span id="reset_current_password_error" class="error_message"></span>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="form_row">
					<div class="content_form_label pull-left">
						<label for="reset_new_password" class="form_label pull-right">New Password:</label>
						<div class="clearfix"></div>
					</div>
					<div class="content_form_input pull-left">
						<input id="reset_new_password" name="up_n_password" type="password" autocomplete="off" class="form_field"/><br/>
				 		<span id="reset_new_password_error" class="error_message"></span>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="form_row">
					<div class="content_form_label pull-left">
						<label for="reset_confirm_new_password" class="form_label pull-right">Confirm New Password:</label>
						<div class="clearfix"></div>
					</div>
					<div class="content_form_input pull-left">
						<input id="reset_confirm_new_password" name="up_cn_password" type="password" autocomplete="off" class="form_field"/><br/>
				 		<span id="reset_confirm_new_password_error" class="error_message"></span><br/>
				 		
				 		<div class="button red_button submit_button pull-right" onclick="submitResetPassword();">Save</div>
					</div>
					<div class="clearfix"></div>
				</div>
			</form>
		</div>
	</div>
</div>
<div class="content_bottom">Have question about your account? Email us at <a href="mailto:sales@bmgww.com" target="_top"><u>sales@bmgww.com</u></a> for assistance.</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/portfolio.html.erb
<div class="content_title">Account Settings</div>
<%= render partial: "account_tab_menu.html.erb" %>

<div class="content_outer">
	<div class="content_core">
		<%
		
		@sub_users = @db[:user].find('company_id' => @user_company_id)
		@db.close
		
		@network = @db[:network].find('company_id' => @user_company_id)
		@db.close
		
		@network_arr = []
		@sub_users_arr = []
		
		
		
		@network_hash = {}
		@network_id_arr = []
		@sub_users_id_arr = []
		
		
		if @sub_users.count.to_i > 0
			@sub_users.each do |sub_users|
				@sub_users_arr << sub_users
				@sub_users_id_arr << sub_users["id"]
			end
		end
		
		
		if @network.count.to_i > 0
			@network.each do |network|
				@network_arr << network
				
				@network_id_arr << network["id"].to_s
				@network_hash["id"+network["id"].to_s] = network
			end
		end
		
		
		
		@user_allow_network_hash = {}
		@user_allow_network = @db[:network_user].find("user" => { "$in" => @sub_users_id_arr})
		
		@user_allow_network.each do |user_allow_network|
			if @user_allow_network_hash["id"+user_allow_network["user"].to_s]
				@user_allow_network_hash["id"+user_allow_network["user"].to_s] += "," +user_allow_network["network_id"].to_s
			else
				@user_allow_network_hash["id"+user_allow_network["user"].to_s] = user_allow_network["network_id"].to_s
			end
		end
		
		
		
		if @sub_users_arr.count.to_i > 0
			@sub_users_arr.each do |subuser|		
				if session[:user_id] != subuser["id"].to_i
					
					user_network_id_array = []
					not_user_network_id_array = []
					
					if @user_allow_network_hash["id"+subuser["id"].to_s]
						
						user_network_id_array = @user_allow_network_hash["id"+subuser["id"].to_s].split(",")
						user_network_id_array = user_network_id_array.uniq.sort 
						
						not_user_network_id_array = @network_id_arr - user_network_id_array
						
						# concat @network_id_arr
						# concat "<br />".html_safe
						# concat user_network_id_array
						# concat "<br />".html_safe
						# concat	@network_id_arr - user_networl_id_array
					end
					
					# concat "<br /><br />".html_safe
					%>
					
					<div class="portfolio_container">
						<div class="content_item"><%=subuser["username"]%> (<%=subuser["email"]%>)</div>
						
						<div class="content_item">
							<div class="portfolio_select_container">
								<div class="portfolio_select_header button" onclick="toggleHiddenPortfolio(this);">Advertising accounts in this portfolio:<span class="downArrow pull-right"></span></div>
								<div class="portfolio_select_hidden">
									<hr/>
									<form action="" method="post" id="portfolioDeleteForm_<%=subuser["id"]%>" autocomplete="off">
										<input type="hidden" name="user_id" id="delete_user_id" value="<%=subuser["id"]%>">
											<% 
											if user_network_id_array.count.to_i > 0 
												user_network_id_array.each do |user_network_id_array_d|
											%>
													<div class="portfolio_select_option"><input type="checkbox" name="network_id_array[]" value="<%=@network_hash["id"+user_network_id_array_d.to_s]["id"]%>"/><%=@network_hash["id"+user_network_id_array_d.to_s]["name"]%></div>
											<% 
												end
											end 
											%>
									</form>
									<hr/>
									<div class="portfolio_select_button_container">
										<input type="checkbox" value="<%=subuser["id"]%>" onchange="selectAllPortfolioOption(this,'portfolioDeleteForm_<%=subuser["id"]%>');"/>Select all
										<div class="button red_button submit_button central_button" onclick="submitPortfolioDelete('portfolioDeleteForm_<%=subuser["id"]%>');">Remove from this portfolio</div>
									</div>
								</div>
							</div>
						</div>
						
						<div class="content_item">
							<div class="portfolio_select_container">
								<div class="portfolio_select_header button" onclick="toggleHiddenPortfolio(this);">Select Advertising account to add to this portfolio <span class="downArrow pull-right"></span></div>
								<div class="portfolio_select_hidden">
									<hr/>
									<form action="" method="post" id="portfolioAddForm_<%=subuser["id"]%>" autocomplete="off">
										<input type="hidden" name="user_id" id="add_user_id" value="<%=subuser["id"]%>">
										<%
										
										if not_user_network_id_array.count.to_i > 0 
											not_user_network_id_array.each do |not_user_network_id_array_d|
										%>
												<div class="portfolio_select_option"><input type="checkbox" name="network_id_array[]" value="<%=@network_hash["id"+not_user_network_id_array_d.to_s]["id"]%>"/><%=@network_hash["id"+not_user_network_id_array_d.to_s]["name"]%></div>
										<% 
											end
										end 
										%>
									</form>
									<hr/>
									<div class="portfolio_select_button_container">
										<input type="checkbox" value="<%=subuser["id"]%>" onchange="selectAllPortfolioOption(this,'portfolioAddForm_<%=subuser["id"]%>');"/>Select all
										<div class="button red_button submit_button central_button" onclick="submitPortfolioAdd('portfolioAddForm_<%=subuser["id"]%>');">Add to this portfolio</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					
					<%
				end
			end
		end
		
		%>
		
		
		<!-- <div class="portfolio_container">
			<div class="content_item">John Smith (john@smith.com)</div>
			<div class="content_item"><span class="remove_icon button" title="remove" onclick=""></span>Qihoo 360: BMG - Asia</div>
			<div class="content_item"><span class="remove_icon button" title="remove" onclick=""></span>BMG - North America</div>
			<div class="content_item">
				<div class="portfolio_select_container">
					<div class="portfolio_select_header button" onclick="toggleHiddenPortfolio(this);">Select Advertising account to add to this portfolio <span class="downArrow pull-right"></span></div>
					<div class="portfolio_select_hidden">
						<hr/>
						<form action="" method="post" id="portfolioForm_1" autocomplete="off">
							<div class="portfolio_select_option"><input type="checkbox" name="account_array[]" value="apihotel@sogou.com"/>apihotel@sogou.com</div>
							<div class="portfolio_select_option"><input type="checkbox" name="account_array[]" value="apihotel@sogou.com"/>apihotel@sogou.com</div>
							<div class="portfolio_select_option"><input type="checkbox" name="account_array[]" value="apihotel@sogou.com"/>apihotel@sogou.com</div>
						</form>
						<hr/>
						<div class="portfolio_select_button_container">
							<input type="checkbox" value="1" onchange="selectAllPortfolioOption(this,'portfolioForm_1');"/>Select all
							<div class="button red_button submit_button central_button" onclick="">Submit</div>
						</div>
					</div>
				</div>
			</div>
		</div> -->
		

	</div>
</div>
<div class="modal fade" id="portfolio_error_modal" tabindex="-1" role="dialog" aria-labelledby="portfolio_error_modal_label">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-body">
				<div class="modal_container">
					<div id="portfolio_error_content" class="modal_title user_remove_title"></div>
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div class="button red_button submit_button" onclick="$('#portfolio_error_modal').modal('hide');">OK</div>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/tracking.html.erb
<div class="content_title">Account Settings</div>
<%= render partial: "account_tab_menu.html.erb" %>

<%
@company_id = @user_company_id

if @user_company_id.to_i < 4
	@company_id = @company_id + 1
end

script = <<EOL
<script type="text/javascript">
var _dynm = _dynm || [];
(function() {
    function a(a) {
        return null != a ? a.toString().substring(0, 1024) : ""
    }
    var gl = {'tag_version':'ut0.1','companyid': #{@company_id}}; 
    var prm = {};
    prm.params1 = '';
    prm.params2 = '';
    prm.params3 = '';
    prm.params4 = '';
    prm.params5 = '';
    prm.params6 = '';
    prm.params7 = '';
    prm.params8 = '';
    prm.params9 = '';
    prm.params10 = '';
    
    gl.prm = prm;
    _dynm.push(gl);
    for (var b = [], c = 0; c < _dynm.length; c++){
        if (_dynm[c].hasOwnProperty("tag_version") && _dynm[c].hasOwnProperty("companyid") && _dynm[c].hasOwnProperty("prm")){
            b.push("rn=" + (Math.floor((1e8 - 2) * Math.random()) + 1));
            for (var d in _dynm[c]){
                if (_dynm[c].hasOwnProperty(d)){
                    if ("object" == typeof _dynm[c][d]){
                        for (var e in _dynm[c][d]) 
                            _dynm[c][d].hasOwnProperty(e) && b.push("prm." + e + "=" + _dynm[c][d][e]);
                    }else{
                        b.push(d + "=" + _dynm[c][d]);
                    }
                }
            }
            _dynm[c].p = 1;
            var f = document.createElement("script");
            f.type = "text/javascript"; 
            f.async = !0; 
            f.charset = "UTF-8"; 
            f.src = "https://t.adeqo.com/event?" + b.join("&");
            var a = document.getElementsByTagName("script")[0];
            a.parentNode.insertBefore(f, a)
        }
    }

})();
</script>
EOL
 
 
 
 
noscript = <<EOL 

			<noscript>
				<img style="border-style:none;" alt="" src="https://t.adeqo.com/event?tag_version=ut0.1&companyid=#{@user_company_id}&prm.params1=&prm.params2=&prm.params3=&prm.params4=&prm.params5=&prm.params6=&prm.params7=&prm.params8=&prm.params9=&prm.params10=" width="1" height="1">
			</noscript>

EOL

%>

<div class="content_outer">
	<div class="content_core">
		<div class="content_core_big_title">
			Pixel Code
		</div>
		<hr/>
		<div class="content_core_title">
			Copy the code below and paste it between the &lt;head&gt; and &lt;/head&gt; in your website code.
		</div>
		<div class="tracking_code_container">
			<div class="tracking_code_core" id="toBeCopied" contenteditable="true">
				<%=script.to_s%>				
				
				<br /><br /><br />
				
				<%=noscript.to_s%>
				
			</div>
			<hr/>
			<div class="tracking_code_button_container">
				<div class="button red_button submit_button central_button" onclick="autoSelect('toBeCopied');">Copy Scripts</div>
			</div>
		</div>
	</div>
</div>