config/routes.rb
Rails.application.routes.draw do
  
  resources :networks

  resources :users
  resources :homes
  
  
  
  root 'application#not_found'
  
  
  
  
  get '/test' => 'homes#index'
  
  get '/cleaneventfile' => 'application#cleaneventfile'
  get '/exporteventfile' => 'application#exporteventfile'
  get '/geteventfile' => 'application#geteventfile'
  
  get '/cleanclickfile' => 'application#cleanclickfile'
  get '/exportclickfile' => 'application#exportclickfile'
  get '/getclickfile' => 'application#getclickfile'
  
  get '/cleanexportfile' => 'application#cleanexportfile'
  get '/cleanlogfile' => 'application#cleanlogfile'
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  get '/getevent' => 'application#getevent'
  get '/event' => 'application#event'
  
  
  get '/getclick' => 'application#getclick'
  get '/click' => 'application#click'
  
  
  
  
  
    
  
  
  
  
  
  
   
  get '*unmatched_route' => 'application#not_found'

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]
  before_action :authuser, except: [:index,:demo,:contact_us,:send_demo_email,:send_contact_us_email]
  # before_action :loginuser, only: [:index]
  
  layout "application", :only => [ :index,:demo,:contact_us]  
  layout "home", :except => [ :index,:demo,:contact_us ] 
  
  require 'savon'
  require "azure"
  
  require 'rubygems'
  require 'mongo'
  
  # GET /homes
  # GET /homes.json
  
  def contact_us
      @title = " | Contact Us"
  end
  
  def demo
      @title = " | Request Demo"
  end
  
  def send_contact_us_email
      @contact_name = params[:contact_name]
      @contact_email = params[:contact_email]
      @contact_subject = params[:contact_subject]
      @contact_message = params[:contact_message]
      
      if @contact_name.to_s == "" || @contact_email.to_s == "" || @contact_subject.to_s == "" || @contact_message.to_s == ""
          data = {:message => "miss require field", :status => "false"}
          return render :json => data, :status => :ok
      end
      
      
      begin
          mg_client = Mailgun::Client.new("key-63ad3b57013d96ecf8b581b02c917dbe")  
          mb_obj = Mailgun::MessageBuilder.new()
       
          mb_obj.set_from_address("do-not-reply@adeqo.com", {"first"=>"Adeqo", "last" => ""});
          
          
          # mb_obj.add_recipient(:cc, "bpo@bmgww.com", {"first" => "", "last" => ""});  
          mb_obj.add_recipient(:to, "adeqo@bmgww.com", {"first" => "", "last" => ""});
        #   mb_obj.add_recipient(:cc, "jkwan@bmgww.com", {"first" => "", "last" => ""});
          mb_obj.add_recipient(:cc, "cjchen@bmgww.com", {"first" => "Chris", "last" => "Chen"});
          mb_obj.add_recipient(:cc, "xfung@bmgww.com", {"first" => "", "last" => ""});
          
          mb_obj.set_subject("Adeqo | Contact Us");  
          # mb_obj.set_text_body(result_msg);
          
          result_msg = "<p>Name:"+@contact_name+"</p>"
          result_msg = result_msg + "<p>Email:"+@contact_email+"</p>"
          result_msg = result_msg + "<p>Subject"+@contact_subject+"</p>"
          result_msg = result_msg + "<p>Message:<br /><br />"+@contact_message+"</p>"
          
           
          mb_obj.set_html_body(result_msg);
          mg_client.send_message("china.adeqo.com", mb_obj)
          
      rescue Exception
          data = {:message => "email error", :status => "false"}
          return render :json => data, :status => :ok
      end
      
      data = {:message => "email done", :status => "true"}
      return render :json => data, :status => :ok
      
  end
  
  def send_demo_email
    
      @personal_demo_first_name = params[:personal_demo_first_name]
      @personal_demo_last_name = params[:personal_demo_last_name]
      @personal_demo_company_name = params[:personal_demo_company_name]
      @personal_demo_business_email = params[:personal_demo_business_email]
      @personal_demo_phone_number = params[:personal_demo_phone_number]
      @personal_demo_country = params[:personal_demo_country]
      @personal_demo_help = params[:personal_demo_help]
      
      if @personal_demo_first_name.to_s == "" || @personal_demo_last_name.to_s == "" || @personal_demo_business_email.to_s == ""
          data = {:message => "miss require field", :status => "false"}
          return render :json => data, :status => :ok
      end
      
      begin
          
          mg_client = Mailgun::Client.new("key-63ad3b57013d96ecf8b581b02c917dbe")  
          mb_obj = Mailgun::MessageBuilder.new()
       
          mb_obj.set_from_address("do-not-reply@adeqo.com", {"first"=>"Adeqo", "last" => ""});
          
          mb_obj.add_recipient(:to, "adeqo@bmgww.com", {"first" => "", "last" => ""});
        #   mb_obj.add_recipient(:cc, "jkwan@bmgww.com", {"first" => "", "last" => ""});
          mb_obj.add_recipient(:cc, "cjchen@bmgww.com", {"first" => "Chris", "last" => "Chen"});
          mb_obj.add_recipient(:cc, "xfung@bmgww.com", {"first" => "", "last" => ""});
          
          mb_obj.set_subject("Adeqo | Request Demo");  
          # mb_obj.set_text_body(result_msg);
          
          result_msg = "<p>First Name:"+@personal_demo_first_name+"</p>"
          result_msg = result_msg + "<p>Last Name:"+@personal_demo_last_name+"</p>"
          result_msg = result_msg + "<p>Company Name:"+@personal_demo_company_name+"</p>"
          result_msg = result_msg + "<p>Business Email:"+@personal_demo_business_email+"</p>"
          result_msg = result_msg + "<p>Phone Number:"+@personal_demo_phone_number+"</p>"
          result_msg = result_msg + "<p>Company:"+@personal_demo_country+"</p>"
          result_msg = result_msg + "<p>How can we help:<br /><br />"+@personal_demo_help+"</p>"
          
           
          mb_obj.set_html_body(result_msg);
          mg_client.send_message("china.adeqo.com", mb_obj)
          
      rescue Exception
          
          data = {:message => "email error", :status => "false"}
          return render :json => data, :status => :ok
      end
      
      data = {:message => "email done", :status => "true"}
      return render :json => data, :status => :ok
  end
  
  def index
    # @logger.info "Load Home index "+ @now.to_s
    loginuser()
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  
  def dashboard
  end


  def dashboarddetail
  end
  
  
  def getdashboard
    
      # @logger.info "Load Home getdashboard "+ @now.to_s
      @start_date = params[:start_date]
      @end_date = params[:end_date]
      @channel_array = params[:channel_array]
      @account_id_array = params[:account_array]
      
      if @channel_array.nil?
          @channel_array = []
      end
      
      if @end_date.nil?
          request_start_date = @today - 1.days
          @end_date = request_start_date.strftime("%Y-%m-%d")
      else
          session[:end_date] = @end_date.to_date
          @end_date = @end_date.to_date + 1.days
          @end_date = @end_date.strftime("%Y-%m-%d")
      end
      
      if @start_date.nil?
          request_start_date = @today - 8.days
          @start_date = request_start_date.strftime("%Y-%m-%d")
      else
          session[:start_date] = @start_date.to_date
          @start_date = @start_date.to_date
          @start_date = @start_date.strftime("%Y-%m-%d")
      end
      
      
      day_range = (@end_date.to_date - @start_date.to_date).to_i
      
      current_day = @today.strftime("%d")
      last_day = Date.today.end_of_month.strftime("%d")
      first_date_of_this_month = Date.today.at_beginning_of_month.strftime("%Y-%m-%d")
      
      @channels = []      
      @request_date = []
      
      @account = []
      
      @user_network_id_array = []
      @user_network_array = []
      
      if session[:user_network_id_array].nil?
        
          @user_network = @db[:network_user].find('user' => session[:user_id].to_i)
          @db.close
          
          @total_network_array = []
          
          @user_network.each do |user_network_d|
              @user_network_id_array << user_network_d["network_id"]
          end
          
          @total_network_array = @db[:network].find('id' => { "$in" => @user_network_id_array}, 'type' => { "$in" => @channel_array})
          @db.close
    
          if @total_network_array.count.to_i > 0
              @user_network_id_array = []
              
               @total_network_array.each do |total_network_array_d|
                  @user_network_id_array << total_network_array_d["id"]
               end
          end
          
          session[:user_network_id_array] = @user_network_id_array.join(",")
      else
          
          if @account_id_array.nil?
            
              @user_network_id_array = session[:user_network_id_array].split(",")
              @user_network_id_array = @user_network_id_array.map(&:to_i)
              
              @total_network_array = @db[:network].find('id' => { "$in" => @user_network_id_array}, 'type' => { "$in" => @channel_array})
              @db.close
              
          else
            
              @account_id_array = @account_id_array.map(&:to_i)
              @user_network_id_array = @account_id_array
              
              @total_network_array = @db[:network].find('id' => { "$in" => @account_id_array})
              @db.close
              
              session[:user_network_id_array] = @user_network_id_array.join(",")
          end
          
      end
          
      
      #account do same thing for other channel
      # session[:user_network_id_array] = nil
      
      
      if @start_date < first_date_of_this_month
        request_date_start_from = @start_date
      else
        request_date_start_from = first_date_of_this_month
      end
      
      @sogou_report_account = @db3[:sogou_report_account].find('network_id' => { "$in" => @user_network_id_array}, 'report_date' => { '$gte' => request_date_start_from.to_s }, 'display' => { "$gt" => 0})
      @db3.close
      
      @report_account_360 = @db3[:report_account_360].find('network_id' => { "$in" => @user_network_id_array}, 'report_date' => { '$gte' => request_date_start_from.to_s }, 'display' => { "$gt" => 0})
      @db3.close
      
      report_account_total_cost_hash = {}
      request_date_hash = {}
      
      # channels[]
      @sogou_object = {}
      @three_sixty_object = {}
      
      @sogou_impressions = 0
      @sogou_clicks = 0
      @sogou_ctr = 0
      @sogou_cost = 0
      @sogou_avg_cpc = 0
      @sogou_avg_pos = 0
      
      @three_sixty_impressions = 0
      @three_sixty_clicks = 0
      @three_sixty_ctr = 0
      @three_sixty_cost = 0
      @three_sixty_avg_cpc = 0
      @three_sixty_avg_pos = 0
      
      @conversion_sogou_count = 0
      @conversion_360_count = 0
      # channels[]
      

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/contact_us.html.erb
<div class="adeqo-container page-contact-us">
  <header>
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container ">
        <div class="navbar-header">
          <button type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" class="navbar-toggle collapsed"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a href="/" class="navbar-brand"><img src="/images/adeqo-logo.png" alt="Adeqo" title="Adeqo" width="132" height="76" class="img-responsive"/></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/">Home</a></li>
            <li class="active"><a href="/contact_us">Contact Us</a></li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <section class="banner">
    <h1>Contact Us</h1>
  </section>
  <section class="content">
    <div class="container">
      <div class="">
        <div class="col-xs-12 col-md-5 contact-us-left-col">
          <div id="msg"></div>
		  <form id="contact_us_form" method="post" class="form">
            <p>Call us at +852 2492 2770 or use below form to get in touch with us</p>
            <div class="contact_form_row">
              <div class="contact_form_input">
                <div class="form-group">
                  <input id="contact_name" name="contact_name" type="text" value="" class="form-control personal_form_text" placeholder="Name*"/>
                </div>
              </div>
              <div class="clearfix"></div>
            </div>
            <div class="contact_form_row">
              <div class="contact_form_input">
                <div class="form-group">
                  <input id="contact_email" name="contact_email" type="text" value="" class="form-control personal_form_text" placeholder="Email*"/>
                </div>
              </div>
              <div class="clearfix"></div>
            </div>
            <div class="contact_form_row">
              <div class="contact_form_input">
                <div class="form-group">
                  <input id="contact_subject" name="contact_subject" type="text" value="" class="form-control personal_form_text" placeholder="Subject*"/>
                </div>
              </div>
              <div class="clearfix"></div>
            </div>
            <div class="contact_form_row">
              <div class="contact_form_input">
                <div class="form-group">
                  <textarea id="contact_message" name="contact_message" cols="40" rows="10" aria-invalid="false" class="form-control contact_form_text" placeholder="Message*"></textarea>
                </div><br/>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 horizontal-center">
                  <button type="button" id="submit_button" form="contact_us_form" class="button red_button submit_button">Send Your Message</button>
                </div>
              </div>
              <div class="clearfix"></div>
            </div>
          </form>
        </div>
        <div class="hidden-xs col-md-2"></div>
        <div class="col-xs-12 col-md-5">
          <div class="block-container">
            <h2><span class="contact_form_title">Visit Us:</span></h2>
            <p>Global Headquarters</p>
            <p>19/F, Tung Chiu Commercial Centre,<br/>193-197 Lockhart Road Wanchai, Hong Kong<br/>Tel: +852 2492 2770<br/>Email: <a href="mailto:sales@bmgww.com">sales@bmgww.com</a></p>
            <div>
              <button class="btn btn-default black-border" type="button" data-toggle="collapse" data-target="#collapseMap" aria-expanded="true" aria-controls="collapseMap">Get Direction</button>
              <div class="collapse in" id="collapseMap">
                <div style="height:400px; width: 100%;"> 
                  <div id="map"></div>
                </div> 
              </div>
            </div>
          </div>
          <div class="block-container">
            <h2><span class="contact_form_title">Join Us:</span></h2>
            <p>We're constantly looking for outstanding<br/>beings to join our team.</p>
            <p>Email us to find our more.</p>
            <a href="mailto:sales@bmgww.com" class="btn btn-default black-border">Join Us</a>
          </div>
        </div>
      </div>
    </div>
  </section>
  <footer class="footer-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-8">
          <p>Copyright © 2016 Adeqo. <a href="http://www.bmgww.com" target="_blank">Intellectual Property of BMG</a>. All Rights Reserved.</p>
        </div>
        <div class="col-xs-12 col-sm-4">
          <p class="text-right">Terms of use & Privacy Policy</p>
        </div>
      </div>
    </div>
  </footer>
</div>

<script type="text/javascript">


$("#submit_button").click(function(e){
	console.log("submit_button");
	
	var postData = $("#contact_us_form").serializeArray();
	var formURL = "/send_contact_us_email";
	
	$( "#msg" ).hide();
	$( "#msg" ).empty();
	$("#contact_us_form :input").prop("disabled", true);
	
	
	for (i = 0; i < postData.length; i++) {
		
		if(postData[i]["value"] == ""){
			$( "#msg" ).append( "<p style='color:red;'>Please fill in the required field.</p>" );
			$( "#msg" ).show();
			$("#contact_us_form :input").prop("disabled", false);
			return;
		}
		
		if(postData[i]["name"] == "contact_email"){
			var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
			if(regex.test(postData[i]["value"]) == false){
				$( "#msg" ).append( "<p style='color:red;'>Please make sure your email is in correct format.</p>" );
				$( "#msg" ).show();
				$("#contact_us_form :input").prop("disabled", false);
				return;		
			}
		}
	}
	
	
	$.ajax({
		url : formURL,
		type: "POST",
		data : postData,
		success:function(data, textStatus, jqXHR) 
		{
			if(data['status'] == "true"){
				$( "#msg" ).append( "<p style='color:green;'>Thanks for your email, we will reply to you shortly!</p>" );
				$( "#msg" ).show();
				$( "#contact_us_form" )[0].reset();
				$("#contact_us_form :input").prop("disabled", false);
				
				$( "#msg" ).delay(2500).slideUp(850);
			}else{
				$( "#msg" ).append( "<p style='color:red;'>Something wrong with your data, please make sure you type in the correct format.</p>" );
				$( "#msg" ).show();
				$("#contact_us_form :input").prop("disabled", false);
			}
		},
		error: function(jqXHR, textStatus, errorThrown) 
		{
			$( "#msg" ).append( "<p style='color:red;'>Our service is too busy, please try again in a few minutes.</p>" );
			$( "#msg" ).show();
			$("#contact_us_form :input").prop("disabled", false);
		}
	});
    e.preventDefault();
});
</script>

<script>
var map;
function initMap() {
  var myLatLng = {lat: 22.278503, lng: 114.1722743};

  // Create a map object and specify the DOM element for display.
  map = new google.maps.Map(document.getElementById('map'), {
    center: myLatLng,
    scrollwheel: false,
    zoom: 17
  });

  // Create a marker and set its position.
  var marker = new google.maps.Marker({
    map: map,
    position: myLatLng,
    title: '19/F, Tung Chiu Commercial Centre, 193-197 Lockhart Road, Wanchai, Hong Kong'
  });
}
</script>
<script async defer src="http://maps.google.cn/maps/api/js?key=&signed_in=false&amp;libraries=places&amp;language=en&amp;callback=initMap"></script>

app/views/homes/demo.html.erb
<div class="adeqo-container page-personal-demo">
  <header>
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container ">
        <div class="navbar-header">
          <button type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" class="navbar-toggle collapsed"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a href="/" class="navbar-brand"><img src="/images/adeqo-logo.png" alt="Adeqo" title="Adeqo" width="132" height="76" class="img-responsive"/></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/">Home</a></li>
            <li><a href="/contact_us">Contact Us</a></li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <section class="banner">
    <h1>Personal Demo</h1>
  </section>
  <section>
    <div class="container">
      <div class="row">
        <div class="personal_information_form col-sm-8 col-sm-push-2 col-sm-12 head-title">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 head-title">
          	<div class="text-center" id="msg">
          	</div>
            <div class="text-center">To learn how to take your PR and social media marketing programs to the next level with Adeqo, fill out the form below and one of our consultants will get in touch right away to schedule a demo</div>
          </div>
          <div class="content_form">
            <form id="personal_form" method="post" class="form">
              <div class="personal_demo_form_row col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="personal_form_input col-lg-6 col-md-6 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <input id="personal_demo_first_name" name="personal_demo_first_name" type="text" value="" class="form_field form-control personal_form_text" placeholder="First Name*"/>
                  </div>
                </div>
                <div class="personal_form_input col-lg-6 col-md-6 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <input id="personal_demo_last_name" name="personal_demo_last_name" type="text" value="" class="form_field form-control personal_form_text" placeholder="Last Name*"/>
                  </div>
                </div>
                <div class="clearfix"></div>
              </div>
              <div class="personal_demo_form_row col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="personal_form_input col-lg-6 col-md-6 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <input id="personal_demo_company_name" name="personal_demo_company_name" type="text" value="" class="form_field form-control personal_form_text" placeholder="Company Name"/>
                  </div>
                </div>
                <div class="personal_form_input col-lg-6 col-md-6 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <input id="personal_demo_business_email" name="personal_demo_business_email" type="text" value="" class="form_field form-control personal_form_text" placeholder="Business Email*"/>
                  </div>
                </div>
                <div class="clearfix"></div>
              </div>
              <div class="personal_demo_form_row col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="personal_form_input col-lg-6 col-md-6 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <input id="personal_demo_phone_number" name="personal_demo_phone_number" type="text" value="" class="form_field form-control personal_form_text" placeholder="Phone Number"/>
                  </div>
                </div>
                <div class="personal_form_input col-lg-6 col-md-6 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <input id="personal_demo_country" name="personal_demo_country" type="text" value="" class="form_field form-control personal_form_text" placeholder="Country"/>
                  </div>
                </div>
                <div class="clearfix"></div>
              </div>
              <div class="personal_demo_form_row col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="personal_form_input col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <textarea id="personal_demo_help" name="personal_demo_help" cols="40" rows="10" aria-invalid="false" class="form-control personal_form_text" placeholder="How can we help you?"></textarea>
                  </div>
                  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 horizontal-center bottom-btn">
                    <button type="button" id="submit_button" onclick="" form="personal_form" class="button red_button submit_button">Get a Demo</button>
                  </div>
                </div>
                <div class="clearfix"></div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <footer class="footer-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-8">
          <p>Copyright © 2016 Adeqo. <a href="http://www.bmgww.com" target="_blank">Intellectual Property of BMG</a>. All Rights Reserved.</p>
        </div>
        <div class="col-xs-12 col-sm-4">
          <p class="text-right">Terms of use & Privacy Policy</p>
        </div>
      </div>
    </div>
  </footer>
</div>


<script type="text/javascript">

$("#submit_button").click(function(e){
	var postData = $("#personal_form" ).serializeArray();
	var formURL = "/send_demo_email";
	
	$( "#msg" ).hide();
	$( "#msg" ).empty();
	$("#personal_form :input").prop("disabled", true);
	
	// console.log(postData);
	
	for (i = 0; i < postData.length; i++) {
		
		// console.log(postData[i]["name"]);
		// console.log(postData[i]["value"]);
		
		if(postData[i]["name"] == "personal_demo_first_name" || postData[i]["name"] == "personal_demo_last_name" || postData[i]["name"] == "personal_demo_business_email"){
			if(postData[i]["value"] == ""){
				$( "#msg" ).append( "<p style='color:red;'>Please fill in the required field.</p>" );
				$( "#msg" ).show();
				$("#personal_form :input").prop("disabled", false);
				return;
			}
		}
		
		if(postData[i]["name"] == "personal_demo_business_email"){
			var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
			if(regex.test(postData[i]["value"]) == false){
				$( "#msg" ).append( "<p style='color:red;'>Please make sure your email is in correct format.</p>" );
				$( "#msg" ).show();
				$("#personal_form :input").prop("disabled", false);
				return;		
			}
		}
		
	}
	
	$.ajax({
		url : formURL,
		type: "POST",
		data : postData,
		success:function(data, textStatus, jqXHR) 
		{
			if(data['status'] == "true"){
				$( "#msg" ).append( "<p style='color:green;'>Thanks for your email, we will reply to you shortly!</p>" );
				$( "#msg" ).show();
				$( "#personal_form" )[0].reset();
				$("#personal_form :input").prop("disabled", false);
				
				$( "#msg" ).delay(2500).slideUp(850);
			}else{
				$( "#msg" ).append( "<p style='color:red;'>Something wrong with your data, please make sure you type in the correct format.</p>" );
				$( "#msg" ).show();
				$("#personal_form :input").prop("disabled", false);
			}
		
		},
		error: function(jqXHR, textStatus, errorThrown) 
		{
			$( "#msg" ).append( "<p style='color:red;'>Our service is too busy, please try again in a few minutes.</p>" );
			$( "#msg" ).show();
			$("#personal_form :input").prop("disabled", false);
		}
	});
	
    e.preventDefault();
});
// $("#personal_form").submit();
</script>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>